# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OasisForGamer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OasisForGamer

pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'YYModel'
pod 'FMDB'
pod 'FDFullscreenPopGesture'
pod 'SVProgressHUD'
pod 'Masonry'
pod 'CYLTabBarController'
pod 'MD5Digest' #MD5加密
pod 'SDCycleScrollView' #轮播图、公告轮播
# pod 'JSBadgeView'
# pod 'FlyImage'

end
